# Generated by Django 5.2.6 on 2025-09-15 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categorys',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=256)),
                ('stock', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0.0)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id_movement', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.TextField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('id_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.movement')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
        migrations.AddField(
            model_name='movement',
            name='records',
            field=models.ManyToManyField(through='stock.Record', to='stock.product'),
        ),
    ]
