# Generated by Django 5.2.6 on 2025-09-15 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stock.category'),
            preserve_default=False,
        ),
    ]
