# Generated by Django 5.2.7 on 2025-10-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_product_created_at_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
