# Generated by Django 5.2.6 on 2025-09-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('role', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
