# Generated by Django 5.2.6 on 2025-09-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=256)),
                ('stock', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0.0)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
